
name: markeet
description: Flutter rewrite of your React web app.

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.8
  carousel_slider: ^5.0.0
  provider: ^6.1.2
  go_router: ^14.2.7
  flutter_dotenv: ^5.1.0
  geolocator: ^12.0.0
  connectivity_plus: ^6.0.5
  shared_preferences: ^2.3.2
  dio: ^5.7.0
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  intl: ^0.20.2
  share_plus: ^11.0.0
  fluttertoast: ^8.2.8
  google_fonts: ^6.2.1
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/markeet.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/markeet.png"
  remove_alpha_ios: true
